const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  EMPTY_CART: 'EMPTY_CART'
};

export default CartActionTypes;
